version: '3.1'

services:
        frontend:
                container_name: frontend-prod
                depends_on:
                        - database 
                        - backend
                network_mode: service:database
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
        database: 
                container_name: db-prod
                image: postgres:alpine
                environment:
                        - POSTGRES_USER=user
                        - POSTGRES_PASSWORD=secure1
                        - POSTGRES_DB=prod_db
                ports:
                        - "5432:5432"
                        - "3000:3000"
                        - "80:80"
        backend:
                container_name: backend-prod
                network_mode: service:database
                depends_on:
                        - database
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                environment:
                        - NODE_ENV=production
                        - DB_CONNECTION=postgres://user:secure1@database/prod_db